# PYTHON NUMPY CHECKPOINT

 Create a numpy array called "grades" that contains the following grades: **[85, 90, 88, 92, 95, 80, 75, 98, 89, 83]**

1. Create a new file called "grades_analysis.py"
2. Import the numpy library and create the "grades" array as specified above.
3. Use numpy functions to calculate the mean, median, and standard deviation of the grades.
4. Use numpy function to find the maximum and minimum of the grades.
5. Use numpy function to sort the grades in ascending order.
6. Use numpy function to find the index of the highest grade in the array.
7. Use numpy function to count the number of students who scored above 90.
8. Use numpy function to calculate the percentage of students who scored above 90.
9. Use numpy function to calculate the percentage of students who scored below 75.
10. Use numpy function to extract all the grades above 90 and put them in a new array called "high_performers".
11. Create a new array called "passing_grades" that contains all the grades above 75.
12. Print the result of all the above steps.

**Note:**

- to calculate percentage use **numpy.mean(grades > 90) * 100**
- to extract the grades above 90 use grades **[grades > 90]**
- to extract the grades above 75 use grades **[grades > 75]**

You can use other numpy functions as well to analyze the data as you want. The above steps are just examples of what can be done.

In [1]:
#Import the numpy library  

import numpy as np

In [2]:
#creating the "grades" array as specified above.

grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [3]:
#Using numpy functions to calculate the mean, median, and standard deviation of the grades.
mean_val = np.mean(grades)
print("Mean value:", mean_val.round(4))

median_val = np.median(grades)
print("Median value:", median_val.round(4))

std_dev_val = np.std(grades)
print("Standard deviation:", std_dev_val.round(4) )

Mean value: 87.5
Median value: 88.5
Standard deviation: 6.5917


In [4]:
#Using numpy function to find the maximum and minimum of the grades.
max_val = np.max(grades)
print("Maximum value:", max_val)

min_val = np.min(grades)
print("Minimum value:", min_val)

Maximum value: 98
Minimum value: 75


In [5]:
#Using numpy function to sort the grades in ascending order

sorted_arr = np.sort(grades)
sorted_arr

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

In [6]:
#Using numpy function to find the index of the highest grade in the array.

highest_grade_idx = np.argmax(grades)
highest_grade_idx

7

In [10]:
#Using numpy function to count the number of students who scored above 90.

above_90 = np.sum(grades > 90)
above_90

3

In [11]:
#Using numpy function to calculate the percentage of students who scored above 90

above_90_per = (above_90/len(grades)) * 100
above_90_per

30.0

In [14]:
#Using numpy function to calculate the percentage of students who scored below 75

above_75_per = ((np.sum(grades < 75))/len(grades)) * 100
above_75_per

0.0

In [15]:
#Using numpy function to extract all the grades above 90 and put them in a new array called
#"high_performers".

high_performers = grades[grades > 90]
high_performers

array([92, 95, 98])

In [16]:
#Creating a new array called "passing_grades" that contains all the grades above 75.

passing_grades = grades[grades > 75]
passing_grades

array([85, 90, 88, 92, 95, 80, 98, 89, 83])

In [17]:
print("Grade Analysis:")
print("----------------")
print("Grades:", grades)
print()
print("Mean grade:", mean_val)
print()
print("Median grade:", median_val)
print()
print("Standard Deviation of grades:", std_dev_val)
print()
print("Maximum grade:", max_val)
print()
print("Minimum grade:", min_val)
print()
print("Sorted grades:", sorted_arr)
print()
print("Index of Highest grade:",highest_grade_idx)
print()
print("Number of students with grades Above 90:", above_90)
print()
print("Percentage of students with grades Above 90%:", above_90_per)
print()
print("High performers (grades Above 90):", high_performers)
print()
print("Good performers (grades Above 75):", passing_grades)


Grade Analysis:
----------------
Grades: [85 90 88 92 95 80 75 98 89 83]

Mean grade: 87.5

Median grade: 88.5

Standard Deviation of grades: 6.591661399070799

Maximum grade: 98

Minimum grade: 75

Sorted grades: [75 80 83 85 88 89 90 92 95 98]

Index of Highest grade: 7

Number of students with grades Above 90: 3

Percentage of students with grades Above 90%: 30.0

High performers (grades Above 90): [92 95 98]

Good performers (grades Above 75): [85 90 88 92 95 80 98 89 83]
